# action.yml
name: 'build in docker'
description: 'build in docker'
inputs:
  shell_main:
    description: 'main'
    required: true
    default: 'action.sh'
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/main.sh'

