# action.yml
name: 'centos7'
description: 'build in centos7'
inputs:
  shell_main:
    description: 'main'
    required: true
    default: 'action.sh'
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/main.sh'
  pre-entrypoint: '/setup.sh'
  post-entrypoint: '/cleanup.sh'

