# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  shell_main:
    description: 'main'
    required: true
    default: 'action.sh'
  shell_pre:
    description: 'pre'
    required: true
    default: 'setup.sh'
  shell_post:
    description: 'post'
    required: true
    default: 'cleanup.sh'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.shell_main }}
    - ${{ inputs.shell_pre }}
    - ${{ inputs.shell_post }}
  pre-entrypoint: '/setup.sh'
  entrypoint: '/main.sh'
  post-entrypoint: '/cleanup.sh'

